//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurtovCheckOut.Components.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsApplication
    {
        public int id { get; set; }
        public Nullable<int> idApplication { get; set; }
        public Nullable<int> idDetail { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Details Details { get; set; }
        public virtual InWorkApplication InWorkApplication { get; set; }
    }
}
