//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurtovCheckOut.Components.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InWorkApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InWorkApplication()
        {
            this.DetailsApplication = new HashSet<DetailsApplication>();
        }
    
        public int id { get; set; }
        public Nullable<int> idApplication { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<System.DateTime> DateInWork { get; set; }
        public Nullable<System.DateTime> DateDone { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> idPriority { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsApplication> DetailsApplication { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual User User { get; set; }
    }
}
