//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurtovCheckOut.Components.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BurtovCheckOutEntities : DbContext
    {
        public BurtovCheckOutEntities()
            : base("name=BurtovCheckOutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<DetailOrder> DetailOrder { get; set; }
        public virtual DbSet<Details> Details { get; set; }
        public virtual DbSet<DetailsApplication> DetailsApplication { get; set; }
        public virtual DbSet<InWorkApplication> InWorkApplication { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
